### ISSUE TITLE
Running Kore w/o https

### ISSUE THREAD

**Issue by ryanmjacobs** [jorisvink/kore#33] opened 2015-01-30 05:11 UTC
Is it possible to run Kore without https?

**Comment by jorisvink** [comment] 2015-01-30 07:49
Hey,

While it's not officially supported (read: I *strongly* discourage doing so) there is a BENCHMARK environment variable you can use to build Kore without SSL.

```
# make BENCHMARK=1
```

**Comment by apfohl** [comment] 2015-01-30 08:43
I wrote a blog post about: http://apfohl.com/posts/running-kore-in-production-behind-nginx-proxy/

**Comment by ryanmjacobs** [comment] 2015-01-30 08:55
Thanks, `make BENCHMARK=1` worked perfectly.

In the future, it would be nice if plain http was officially supported. Maybe we could just pass in an option to not use SSL. Something like `-w` for "without-ssl".

**Comment by thorduri** [comment] 2015-01-30 10:04
I think one best parts about Kore is the fact that plain http is a hassle and TLS is a 'built-in'.

**Comment by jorisvink** [comment] 2015-01-30 11:15
Kore will not be getting a run time option to turn off TLS.

**Comment by james2doyle** [comment] 2015-01-30 14:42
Most browsers throw a warning if they can't validate the source of a SSL certificate, so self-signed certs don't really make sense. I guess if people want to spend an additional $130-$180 for the cert, on top of a VPS, that is fine.

Having a flag for turning it off during development would be kinda nice. I had to manually add the cert to my keyring, which isn't the worst process in the world. It was just a few additional steps.

**Comment by jorisvink** [comment] 2015-01-30 15:54
I am glad you shared how you fixed this at your end, however I am personally not bothered with the warnings Chrome throws at me when I am talking to Kore its generated self-signed certs.

I can see how that is an issue for some, but as you said there are existing solutions to that problem (adding it to your keyring) or adding an exception in your browser etc.

**Comment by apfohl** [comment] 2015-01-31 17:00
You could also turn TLS off while compiling it on your development machine and use TLS in production.

**Comment by thorduri** [comment] 2015-01-31 17:26
@apfohl Parity between development, staging and production is paramount.

This whole thought of "no TLS in dev", "terminate TLS at the edge", "provide buttons to turn off TLS" etc
needs to die in a fire.

**Comment by jorisvink** [comment] 2015-02-02 21:09
Closing this issue as it has been resolved.

**Closed by jorisvink** 2015-02-02 21:09 UTC

**Comment by lordnynex** [comment] 2015-05-17 04:13
@jorisvink I know the issue is closed but I just want to interject that building without SSL would be beneficial. 

In my case, I would like to leverage Kore to create a set of microservices inside a private cluster. In my case, inter-subnet communication doesn't really need SSL. There are also places in my infrastructure where service communication does happen over SSL, however, my existing load balancers handle SSL offloading for me. At my request volume, SSL termination on the application node costs CPU resources that would be best spent servicing the request. If I've made an investment in SSL offloading/acceleration modules at the hardware level, the proposition to use Kore now comes at a financial cost.

Fundamentally, I like the required SSL for internet facing services. IMHO, there are few projects like this that are so well rounded. When I first came across Kore about a year ago I had to use something else because of the crypto overhead.

**Comment by jorisvink** [comment] 2015-05-17 08:25
@lordnynex $ make BENCHMARK=1

Completely kills TLS. It is there as a non standard build option, but it is there non the less.

**Comment by Houdini** [comment] 2015-06-03 20:14
+1 to run officially kore without https.
https kills a lot of use cases

**Comment by jorisvink** [comment] 2015-06-04 06:04
Note that this compile time build option is now called NOTLS instead of BENCHMARK.

**Comment by michals** [comment] 2015-06-06 07:20
I also whould like to to have option to run with or wiout TLS. Thank you.

**Comment by BenKnigge** [comment] 2016-10-20 03:39
Why can't TLS and HTTPS be configurable options that are on by default? If I were to build anything with Kore I'd put it behind a firewall and load balancer that would handle TLS anyway. It seems like you're discouraging a lot of potential users by forcing TLS and HTTPS.

**Comment by jorisvink** [comment] 2016-10-20 05:44
@BenKnigge So build Kore with the NOTLS option and you're all set to do so.
